on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: terraform-module
          package-name: terraform-google-compute
          include-v-in-tag: false
          changelog-types: '[{ "type": "build", "hidden": true },{ "type": "chore", "hidden": true },{ "type": "ci", "hidden": true },{ "type": "dev", "hidden": true },{ "type": "feat", "section": "Features" },{ "type": "fix", "section": "Bug Fixes" },{ "type": "perf", "section": "Performance Improvements" },{ "type": "refactor", "hidden": true },{ "type": "revert", "section": "Reverted Changes" },{ "type": "style", "hidden": true },{ "type": "test", "hidden": true },{ "type": "docs", "section": "Documentation" },{ "type": "security", "section": "Security Improvements" }]'
